version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19

  pre_build:
    commands:
      - REPOSITORY_URI=$REPOSITORY_URI
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)

  build:
    commands:
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - cat imageDetail.json
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Image Push Completed..."
      - echo "Image Build Completed..."
artifacts:
  files: 
    - 'imageDetail.json'
  name: DockerArtifacts