version: 2.1

executors:
  docker-executor:
    docker:
    - image: circleci/python:3.8 # Use an image that has Docker installed

jobs:
  build-and-push:
    executor: docker-executor
    steps:
    - checkout # Checkout your source code

    - setup_remote_docker: # Set up Docker
        version: 20.10.7
        docker_layer_caching: true

    - run:
        name: Build and push Docker image to DockerHub
        command: |
          # Set environment variables
          export IMAGETAG=cptmarvel  # You can use a different tag if desired

          # Build the Docker image
          docker build -t phyominhtun/hopper-circleci-argocd:$IMAGETAG$CIRCLE_BUILD_NUM .

          # Authenticate with your Docker registry (e.g., Docker Hub)
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

          # Push the Docker image to the registry
          docker push phyominhtun/hopper-circleci-argocd:$IMAGETAG$CIRCLE_BUILD_NUM

workflows:
  version: 2
  hopper-build-flow:
    jobs:
    - build-and-push:
        filters:
          branches:
            only:
            - master
