# file name: hopper-ci.yml
name: Hopper-CI-Workflow
on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: hopper-argocd

jobs:
  create-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
  
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: phyominhtun/${{ env.IMAGE_NAME }}:${{ github.sha }} , phyominhtun/${{ env.IMAGE_NAME }}:latest

    - name: Update docker image information to argocd config repo
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.actor }}/argocd-app-configs
        event-type: argo-new-image-update
        client-payload: '{"image": "phyominhtun/${{ env.IMAGE_NAME }}:${{ github.sha }}"}'